#!/bin/sh
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


blockMesh

checkMesh && surfaceFeatureExtract && snappyHexMesh -overwrite



#-------------------------------------------------------------------
